/*
* This module validates if a given bearer token is valid.
 */

// Import node_modules
const jwt = require('jsonwebtoken')

/*
* The is method validates if a given bearer token is valid.
*
* Input:
*     req.headers.authorization = The Bearer Token generated by a user
* Output:
*     next()                    = if the token is valid
*     returns 401               = if the token is not valid
*     returns 500               = in error case
 */
module.exports = (req, res, next) => {
  try {
    /*
   * Extract the data out of the given JSON Web Token and verify it.
   *
   * A token includes:
   *        - id: User ID
   *        - mail: User Mail
   */
    let token = undefined

    if (req.headers.authorization == undefined) {
      console.log("query")
      token = req.query.token
    } else {
      console.log("header")
      console.log(req.headers.authorization)
      token = req.headers.authorization.split(" ")[1]
    }

    console.log(token)

    const decoded = jwt.verify(token, process.env.JWT_KEY)
    req.userData = decoded

    next()
  } catch (error) {
    console.log("error")
    return res.status(401).json({
      message: 'Auth failed!'
    })
  }
}